[package]
name = "libftdi1-sys"
version = "0.2.0"
authors = ["Denis Lisov <dennis.lissov@gmail.com>"]
keywords = ["bindings", "hardware","ftdi", "libftdi1"]
description = "FFI bindings for libftdi1"
license = "MIT"
homepage = "https://github.com/tanriol/libftdi1-sys"
repository = "https://github.com/tanriol/libftdi1-sys"
edition = "2018"

build = "build.rs"

[dependencies]
libc = "0.2"

[target.'cfg(not(windows))'.build-dependencies]
pkg-config = "0.3"
bindgen = "0.53.2"

[target.'cfg(windows)'.build-dependencies]
vcpkg = "0.2"
bindgen = "0.53.2"
